Setting up rails project
BrightCoders-Proyectos/tribo-web pull request #11
Opened 2020-12-07 17:52 UTC by cardotrejos

Add fresh rails project and some configs:

-.gitignore
-Rubocop
-Rails

2020-12-07 18:06 UTC, ediazjz requested changes
Change `database.yml` to `database.yml.example` and add the first one to `.gitignore` to make it easy for everyone to keep their DB Server credentials configured.

2020-12-07 18:15 UTC, ediazjz approved these changes, later dismissed
Everything looks great!

2020-12-07 18:23 UTC, cardotrejos commented
@YilKanda It's my first time setting up Rubocop, I add gems to development group and test group, also a .rubocop.yml defining some styles for rubocop. Would be nice to get feedback for this task.

2020-12-07 20:32 UTC, YilKanda requested changes

2020-12-07 20:32 UTC, YilKanda commented on Gemfile
> +  gem 'rubocop'
When doing the style guide check with Rubocop, I got this error:

![imagen](https://user-images.githubusercontent.com/12243331/101401224-a2f34080-3897-11eb-93a1-ad2d9484862e.png)

Add this line to the application's Gemfile:

`gem 'rubocop-packaging'`

It should be something like that in the Gemfile:

![imagen](https://user-images.githubusercontent.com/12243331/101401449-01b8ba00-3898-11eb-99ec-c90862140524.png)

2020-12-07 20:32 UTC, YilKanda commented on Gemfile
> +  gem 'rubocop'
Using Rubocop allows us to identify style errors in the code:

For example, in this project, they already come by default:

![imagen](https://user-images.githubusercontent.com/12243331/101401952-b0f59100-3898-11eb-992a-33f531f14966.png)

And using Rubocop, they decrease to:

![imagen](https://user-images.githubusercontent.com/12243331/101402034-cec2f600-3898-11eb-8686-6a9f5505ba24.png)

To execute it, just place in the console, the command:

`rubocop -A
`

2020-12-07 22:28 UTC, YilKanda submitted a review, later dismissed
Looks great to me!

2020-12-08 00:27 UTC, ediazjz approved these changes, later dismissed
Let's go!

2020-12-08 17:14 UTC, jaimelr reviewed
LGTM overall but let's try to start with a clean commit history.

My suggestion is to squash the commits where you apply the changes into the first commit. You can do an interactive rebase with `git rebase -i COMMIT-HASH`, let me know if you agree with this and if you need help performing the rebase.

For example: [This commit](https://github.com/BrightCoders-Proyectos/tribo-web/pull/11/commits/203b7a504aaa894d77330bbe86f75cb488e7ff68) says "adding requested changes" but changes can be squashed into the first commit since it is not adding new features but fixing issues introduced in the first commit. Unless you want to explicitly note that you made a fix there's no need to create another commit.

2020-12-08 17:57 UTC, jaimelr approved these changes
LGTM! 👍

2020-12-08 18:01 UTC, ediazjz approved these changes
👍

2020-12-08 18:07 UTC, YilKanda approved these changes

2020-12-08 18:07 UTC, EduJimenez96 approved these changes

2020-12-08 18:08 UTC, merged

2020-12-09 16:30 UTC, EduJimenez96 reviewed
👍