Information Store Modal
BrightCoders-Proyectos/tribo-web pull request #33
Opened 2020-12-21 23:02 UTC by JacquelineFloresMendez

# Description

Implemented the modal that will allow to visualize the information of the store, when displaying it on the map.
   
  ## Screenshots 

View on the map

![image](https://user-images.githubusercontent.com/69128578/102829716-520e3c80-43ad-11eb-8a0b-2a27eb78a58f.png)

Modal

![image](https://user-images.githubusercontent.com/69128578/102829733-5df9fe80-43ad-11eb-91d7-d759da9501db.png)

2020-12-21 23:25 UTC, EduJimenez96 submitted a review, later dismissed

2020-12-21 23:25 UTC, EduJimenez96 commented on app/views/legal/index.html.erb
> +	</div>
I think, you need to check the identation xd

2020-12-21 23:33 UTC, EduJimenez96 approved these changes, later dismissed

2020-12-22 16:24 UTC, PeterChav01 approved these changes, later dismissed

2020-12-22 22:01 UTC, KarinaDell requested changes
Looks good to me, just fix the indentation as Eduardo said.

2020-12-23 00:10 UTC, YilKanda commented
> Looks good to me, just fix the indentation as Eduardo said.

That had already been fixed yesterday, check it in the commit [af0e2f3](https://github.com/BrightCoders-Proyectos/tribo-web/pull/33/commits/af0e2f39a8294231fc1551c83f73af5e068fd134)

2020-12-23 00:21 UTC, KarinaDell approved these changes

2020-12-23 00:27 UTC, EduJimenez96 approved these changes

2020-12-23 01:41 UTC, OswaldoPineda approved these changes

2020-12-23 17:27 UTC, danielasotomayor99 approved these changes

2020-12-23 17:51 UTC, merged